Blog app: add API endpoints
StarSheriff2/ror-social-scaffold pull request #3
Opened 2021-10-06 15:02 UTC by brenoxav

## Blog app: add API endpoints

- Create an API endpoint to list all posts.
- Create an API endpoint to list all comments for a post.
- API endpoints should receive JSON and respond JSON as well.

2021-10-06 15:29 UTC, AshakaE requested changes
### Hi Team 🙋‍♀️, 

Good job so far! 👌

Pull request is 👌 
Git flow ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


#  Required Changes ♻️ 🚧
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-06 15:29 UTC, AshakaE commented on config/routes.rb
>    end
- [x] Kindly add endpoints for login and registration, I can only see index and show

2021-10-06 22:11 UTC, StarSheriff2 commented on config/routes.rb
>    end
We have added API authentication to the app. However, users can't sign up through the API, only sign in, so you will need to first create a user, before you are able to add a comment to a post, using the API.

2021-10-06 22:14 UTC, StarSheriff2 commented
Detailed instructions about how to use the API calls can be found in the README file. 😊

2021-10-06 23:29 UTC, vichuge commented on config/routes.rb
>    end
- [x] As my companion said, is important to create the endpoint for register, I kindly invite you to add it to your project. 🐶 
![image](https://user-images.githubusercontent.com/20563252/136297213-193cbba1-c1c9-4908-9727-6d63240c0505.png)

2021-10-06 23:30 UTC, vichuge requested changes
# Required Changes ♻️ ♻️ ⚠️ ⚠️ 🚦 🚦 

Hi dear student, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.

![star_wars_almost_there](https://user-images.githubusercontent.com/20563252/121369354-644f4900-c901-11eb-9844-50c85d0f206b.gif)


## Aspects to improve ♻️
_Check the comments under the review._

- [x] Check the comments above the review. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-06 23:30 UTC, vichuge commented on config/routes.rb
>    end
Just do this and you'll finish this project. 🐱

2021-10-07 17:31 UTC, StarSheriff2 commented on config/routes.rb
>    end
Hi, we appreciate the feedback. Although this requirement was not clearly stated in the project description, we have implemented this feature. Users can now register through the Api.

2021-10-07 18:13 UTC, brenoxav commented
Like Arturo said in the previous comment: 

> Although this requirement was not clearly stated in the project description, we have implemented this feature. Users can now register through the Api.

We added detailed instructions on how to use the API in the README.

2021-10-07 18:45 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED ✔🎉**
Hello @brenoxav 👋🏽
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-10-07 19:36 UTC, merged

2021-10-07 22:47 UTC, SpaYco reviewed
Hello 👋,

_This is an additional review as a result of the second opinion request._

Thank you for bringing this to our attention, I'll make sure we update the project requirements so it's clear that signup is part of the project

Thank you for being professional throughout this project, I'm glad your project got approved

Keep rocking 🚀!